import os
import requests
import shutil
import sys
import subprocess

# external volume that persists only the actions runner configuration
CONFIG_DIR = '/runner-config'

# files generated by config.sh that identify and authenticate the runner
CONFIG_FILES = ['.runner', '.credentials', '.credentials_rsaparams']


def resolve_api_url():
    url = os.getenv('GITHUB_REPO_URL') or os.getenv('GITHUB_ORG_URL')
    if not url:
        print('Need GITHUB_REPO_URL or GITHUB_ORG_URL!')
        sys.exit(1)

    scope = 'repos' if os.getenv('GITHUB_REPO_URL') else 'orgs'
    name = url.removeprefix('https://github.com/').rstrip('/')

    return f'https://api.github.com/{scope}/{name}'


def get_runner_token():
    token = os.getenv('GITHUB_RUNNER_TOKEN')
    if token:
        return token

    api_token = os.getenv('GITHUB_API_TOKEN')
    if not api_token:
        print('Need GITHUB_API_TOKEN or GITHUB_RUNNER_TOKEN!')
        sys.exit(1)

    resp = requests.post(
        f'{resolve_api_url()}/actions/runners/registration-token',
        headers={
            'Accept': 'application/vnd.github.v3+json',
            'Authorization': f'token {api_token}',
        }
    )


    if not resp.ok:
        print("Received a negative response from API!")
        sys.exit(1)

    token = resp.json().get('token')
    if token:
        return token

    print("Cannot get token from API!")
    sys.exit(1)


def configure_runner():
    name = os.getenv('GITHUB_RUNNER_NAME')
    url = os.getenv('GITHUB_REPO_URL') or os.getenv('GITHUB_ORG_URL')
    if not name or not url:
        print('Need GITHUB_RUNNER_NAME and GITHUB_REPO_URL or GITHUB_ORG_URL!')
        sys.exit(1)

    token = get_runner_token()
    label = os.getenv('GITHUB_RUNNER_LABEL')
    replace = os.getenv('GITHUB_RUNNER_REPLACE', '')
    work_dir = "_work"

    exe = ['./config.sh',
           '--unattended',
           '--token', token,
           '--name', name,
           '--url', url,
           '--work', work_dir]

    if label:
        exe.extend(['--labels', label])

    if replace.lower() in ('1', 'true', 'yes'):
        exe.append('--replace')

    proc = subprocess.run(exe)

    if proc.returncode != 0:
        command = " ".join(exe).replace(token, "<TOKEN>")
        print(f"{command} failed!")
        sys.exit(1)


def rescue_config():
    # move real config files from runner dir into the persistent volume
    os.makedirs(CONFIG_DIR, exist_ok=True)
    for name in CONFIG_FILES:
        src = os.path.join('/actions-runner', name)
        dst = os.path.join(CONFIG_DIR, name)
        if os.path.exists(src) and not os.path.islink(src):
            shutil.move(src, dst)


def link_config():
    os.makedirs(CONFIG_DIR, exist_ok=True)
    for name in CONFIG_FILES:
        link = os.path.join('/actions-runner', name)
        target = os.path.join(CONFIG_DIR, name)
        if os.path.islink(link) and os.readlink(link) == target:
            continue
        if os.path.lexists(link):
            os.remove(link)
        os.symlink(target, link)


# rescue config files left by a previously interrupted configure_runner()
rescue_config()

if not all(os.path.isfile(os.path.join(CONFIG_DIR, name)) for name in CONFIG_FILES):
    configure_runner()
    # move the files config.sh just wrote into the volume
    rescue_config()

link_config()

if len(sys.argv) > 1:
    os.execv(sys.argv[1], sys.argv[1:])
